### ISSUE TITLE
getting error while running seed

### ISSUE THREAD

**Issue by prashantnirgun** [BayBreezy/crm-nuxt#1]
An error occurred while running the seed command:
Error: Command failed with exit code 1: npx ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have not used the Prisma & tailwind before this if you could fix this will be a great help.

**Comment by BayBreezy** [comment]
Hello @prashantnirgun Thanks for checking the repo.
Can you walk me through what you did before running the command? 
These are the steps taken that made it work for me
- Install dependencies
- Run the `primsa:push` command in the package.json file
- Run the seed command in the package.json file

Try these steps and let me know if you still have this problem. I am in the process of updating the repo now. The packages are outdated lol

**Comment by prashantnirgun** [comment]
Please fix it
01 Warning No license in package.json
02 package.json script there is typo error instead of primsa:push your type primsa:push
03 Error is as follows
```
npm run primsa:push                                                       ─╯

> crm-nuxt@1.0.0 primsa:push
> npx prisma db push

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DB.
  -->  schema.prisma:7
   | 
 6 |   provider = "sqlite"
 7 |   url      = env("DB")
   | 

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.4.1
```

**Comment by BayBreezy** [comment]
Hello,

If you want to add a license to your project, feel free to do so. I don't need a license in this repo as it was just me testing out prisma with nuxt. It was not meant to be a serious application.

- I will update the typo from pimsa --> prisma
- I think you are getting the expiresIn error because you have not create a `.env` file and updated the necessary variables. Ensure that all these values are added and updated 
DB="file:./dev.db"
JWT_SECRET="modify this var"
JWT_EXP_SEC= # add a number here
JWT_EXP_DYS= # add a string here
COOKIE_NAME= # add a string here

**Comment by prashantnirgun** [comment]
is it ok ?
```
DB="file:./dev.db"
JWT_SECRET=";SDFJG3459345034DFLGDGKLD"
JWT_EXP_SEC="50000"
JWT_EXP_DYS="10"
COOKIE_NAME="my_app_cookie"
```
I am still getting the error

**Comment by BayBreezy** [comment]
Hello @prashantnirgun 
I see the issue now. The value for JWT_EXP_DYS is invalid. It should be "10d" for 10 days. Putting 10 as the value will cause jsonwebtoken to set the exp days to 10 milliseconds

**Comment by prashantnirgun** [comment]
Yes its working now, thanks
